### ISSUE TITLE
Pinout not PMOD compatible

### ISSUE THREAD

**Issue by riktw** [wuxx/pico-lab#3]
Hi.

I was missing a nice overview of a pinout, so I made one: https://imgur.com/a/bQP8HdM
To my surprise, the pins do not follow the PMOD pinout. SPI is all over the place so the OLED PMOD board I got does not work.

Could you confirm that this is indeed the pinout?
And is there a reason it is not PMOD compatible?

**Comment by wuxx** [comment]
hello, just notice a typo problem
![image](https://user-images.githubusercontent.com/1648489/175865138-b723e0b1-8887-4db9-ba60-609725d6a7de.png)

**Comment by wuxx** [comment]
and when I design the board, I think all IOs are configurable since we have the PIO, just like FPGA IOs, so if you use PIO with the IOs, it should be no problem, and another reason of the pinout sequence is that I wan't use it with the PMOD-HDMI, so the pins must follow a specific sequence (for example: IO-0 and IO-1 should be a differential pair)

![image](https://user-images.githubusercontent.com/1648489/175865554-78463904-2a0d-4dce-a8e3-0186c00714a5.png)
https://github.com/wuxx/icesugar/blob/master/schematic/pmod_hdmi-v1.1.pdf

**Comment by riktw** [comment]
Ah thanks for the explanation. I am planning to use Nuttx which does not support PIO used as SPI at the moment. If you want, I can upload the pinout diagram source file?

**Comment by wuxx** [comment]
sure, thank you very much :)

**Comment by riktw** [comment]
It should be included, with the 3V3 changed to 5V. Feel free to use the pinout in the repository as you see fit.
As my issue was answered, I will close the ticket, thanks for the explanation again!

![Pinout_rpi](https://user-images.githubusercontent.com/13754249/176270173-ec4ba641-36fa-4aad-8313-0c8ce383743a.svg)

**Comment by wuxx** [comment]
OK, will be merged in the repo, thanks :)
